# note on _self_, copied from hydra.cc
# If you want your primary config to override the values of configs from the Defaults List, append _self_ to the end of the Defaults List.
# If you want the configs from the Defaults List to override the values in your primary config, insert _self_ as the first item in your Defaults List.

defaults:
  - dataset: lc_small
  - model: stcnn_exp_leakyrelu_bn
  - _self_ 


# dataloader options
batch_size: 20
num_workers: 0
shuffle_dataset: True

# optimizer and train loop options
lr: 0.0005 # 5e-3 #1e-5 # 5e-2 # 0.001
clip_max_norm: 0.05 # 0.5 #0.1 #2*0.05 # Can be None
n_epochs: 40 # 150 #400 #400 #300
print_freq: 20 # iterations, how often to print losses within one epoch of training
clip_param:
  pattern1:
    name: .tau # temporal filter time constant
    min: 0.005 # seconds, bound on fly visual system based on photoreceptor response time
    max: null # null will be converted to NoneType in python, torch.clamp treats None as no bound
  pattern2:
    name: .ca_tau
    min: 0.1 # seconds
    max: 1.0 # seconds
  pattern3:
    name: global_ca_tau
    min: 0.35
    max: 0.45
  pattern4:
    name: .n_power
    min: 0.5
    max: 10


# experiment info
expt_path: /groups/card/cardlab/klapoetken/optic_glomeruli/experiments/
expt_name: debug_init
